import { h as head } from "../../chunks/index2.js";
import { t as transparentLogo } from "../../chunks/logo-transparent.js";
import { s as stockCommunity } from "../../chunks/stock-community.js";
import { a as attr } from "../../chunks/attributes.js";
const stockBlog = "/_app/immutable/assets/stock-blog.WIChljdQ.jpg";
const stockFriends = "/_app/immutable/assets/stock-friends.BX76kOMA.jpg";
function _page($$payload) {
  head($$payload, ($$payload2) => {
    $$payload2.title = `<title>Tech Talk Augusta</title>`;
    $$payload2.out += `<meta name="description" content="Join our monthly tech meetup in Augusta, Georgia. Connect with local tech enthusiasts, share ideas, and learn about the latest trends in technology."> <meta name="keywords" content="Tech Meetup, Augusta Georgia, Technology Community, Networking, Monthly Events"> <meta name="author" content="Tech Talk Augusta"> <meta property="og:title" content="Augusta Tech Meetup"> <meta property="og:description" content="Join our monthly tech meetup in Augusta, Georgia. Connect with local tech enthusiasts and learn about the latest trends in technology."> <meta property="og:image" content="https://techtalkaugusta.com/images/og-image.jpg"> <meta property="og:url" content="https://techtalkaugusta.com"> <meta name="twitter:card" content="summary_large_image"> <meta name="twitter:title" content="Augusta Tech Meetup"> <meta name="twitter:description" content="Join our monthly tech meetup in Augusta, Georgia. Connect with local tech enthusiasts and learn about the latest trends in technology."> <meta name="twitter:image" content="https://techtalkaugusta.com/images/twitter-image.jpg">`;
  });
  $$payload.out += `<section class="hero svelte-1ob7tba"><div class="container svelte-1ob7tba"><div class="hero-content svelte-1ob7tba"><img${attr("src", transparentLogo)} alt="Tech Talk Augusta Logo" class="hero-logo svelte-1ob7tba"> <h1>Tech Talk Augusta</h1> <h2 class="svelte-1ob7tba">Building a Thriving Tech Community in Augusta</h2> <p class="hero-text svelte-1ob7tba">Join us in fostering innovation, connection, and equity in Augusta's tech scene.</p></div></div></section> <section class="features svelte-1ob7tba"><div class="container svelte-1ob7tba"><div class="feature-grid svelte-1ob7tba"><div class="feature-card svelte-1ob7tba"><img${attr("src", stockCommunity)} alt="Community members sharing a meal" class="feature-image svelte-1ob7tba"> <div class="feature-content svelte-1ob7tba"><h3 class="svelte-1ob7tba">Community Calendar</h3> <p>Stay updated with all tech events in Augusta.</p> <a href="/events" class="btn btn-primary">View Events</a></div></div> <div class="feature-card svelte-1ob7tba"><div class="feature-content svelte-1ob7tba"><h3 class="svelte-1ob7tba">Event Archive</h3> <p>Access previous talks, events, and presentations.</p> <a href="https://dev.to/techtalkaugusta" class="btn btn-primary">View Past Events</a></div> <img${attr("src", stockBlog)} alt="Person working on computer" class="feature-image svelte-1ob7tba"></div> <div class="feature-card svelte-1ob7tba"><img${attr("src", stockFriends)} alt="Group of friends" class="feature-image svelte-1ob7tba"> <div class="feature-content svelte-1ob7tba"><h3 class="svelte-1ob7tba">Tech Directory</h3> <p>Connect with local tech professionals and companies.</p> <button class="btn btn-primary" disabled>Coming Soon</button></div></div></div></div></section> <section class="cta-section svelte-1ob7tba"><div class="container svelte-1ob7tba"><div class="cta-grid svelte-1ob7tba"><div class="cta-card svelte-1ob7tba"><h3 class="svelte-1ob7tba">Call For Speakers</h3> <p>Share your expertise and inspire others in our community. We're always looking for
					passionate speakers to share their knowledge and experiences.</p> <a href="/forms/call-for-speakers" class="btn btn-secondary">Apply to Speak</a></div> <div class="cta-card svelte-1ob7tba"><h3 class="svelte-1ob7tba">Get in Touch</h3> <p>Have questions or suggestions? We'd love to hear from you!</p> <a href="/forms/contact" class="btn btn-secondary">Contact Us</a></div></div></div></section> <section class="about-section svelte-1ob7tba"><div class="container svelte-1ob7tba"><h2 class="svelte-1ob7tba">Why Augusta?</h2> <p class="lead svelte-1ob7tba">Augusta is a city with a rich history and a bright future, uniquely positioned to become a hub
			for technological growth and innovation.</p> <div class="about-grid svelte-1ob7tba"><div class="about-content"><p>As the home of the Army Cyber Center of Excellence, the Augusta National, Georgia Cyber Center, and
					the Savannah River Nuclear Site, our city is no stranger to world-class projects and cutting-edge
					expertise. Yet, while these institutions bring incredible resources and talent, there's a missing
					piece: support for small businesses, local software developers, and the vibrant downtown community.</p> <h3 class="svelte-1ob7tba">Our Vision</h3> <ul class="feature-list svelte-1ob7tba"><li class="svelte-1ob7tba"><strong>Entrepreneurship in Tech:</strong> Encouraging small businesses to thrive in our
						downtown.</li> <li class="svelte-1ob7tba"><strong>Community Investment:</strong> Tech professionals supporting the arts, education, and local
						equity initiatives.</li> <li class="svelte-1ob7tba"><strong>Educational Growth:</strong> Integrating tech curricula into schools to empower the next
						generation of innovators.</li> <li class="svelte-1ob7tba"><strong>Inclusivity and Opportunity:</strong> Using technology to reduce poverty and increase equality
						across our city.</li></ul> <p>Augusta has the talent, the drive, and the resources to stand on its own two feet as a tech leader—not
					just for government contractors but for everyone who calls this city home. Together, we can build
					a community where technology uplifts every corner of Augusta. Join us in making it happen.</p></div></div></div></section> <section class="discord-section svelte-1ob7tba"><div class="container svelte-1ob7tba"><div class="discord-grid svelte-1ob7tba"><div class="discord-content svelte-1ob7tba"><h2 class="svelte-1ob7tba">Join Our Discord Community</h2> <p class="lead svelte-1ob7tba">Connect with tech enthusiasts, share resources, and stay updated with the latest events.</p> <ul class="discord-features svelte-1ob7tba"><li class="svelte-1ob7tba">Real-time discussions and networking</li> <li class="svelte-1ob7tba">Automated event reminders</li> <li class="svelte-1ob7tba">Tech resource sharing</li> <li class="svelte-1ob7tba">Community polls and feedback</li> <li class="svelte-1ob7tba">Role-based channels and access</li></ul> <div class="discord-cta svelte-1ob7tba"><a href="https://discord.gg/techtalkaugusta" class="btn btn-primary" target="_blank" rel="noopener noreferrer">Join Discord Server</a></div></div> <div class="discord-image svelte-1ob7tba"><img${attr("src", stockCommunity)} alt="Discord community members" class="svelte-1ob7tba"></div></div></div></section> <section class="whats-next-section svelte-1ob7tba"><div class="container svelte-1ob7tba"><h2 class="svelte-1ob7tba">What's Next</h2> <p class="lead svelte-1ob7tba">Stay tuned for exciting events and initiatives coming to Augusta's tech community.</p> <div class="whats-next-grid svelte-1ob7tba"><div class="whats-next-card svelte-1ob7tba"><div class="card-icon svelte-1ob7tba">🎯</div> <h3 class="svelte-1ob7tba">Monthly Tech Talks</h3> <p class="svelte-1ob7tba">Join us every month for engaging presentations on cutting-edge technology topics,
					from AI to cybersecurity.</p> <a href="/calendar" class="btn btn-secondary">View Schedule</a></div> <div class="whats-next-card svelte-1ob7tba"><div class="card-icon svelte-1ob7tba">💻</div> <h3 class="svelte-1ob7tba">Code &amp; Coffee</h3> <p class="svelte-1ob7tba">Weekly casual meetups where developers can work on projects together,
					share knowledge, and network.</p> <button class="btn btn-secondary" disabled>Coming Soon</button></div> <div class="whats-next-card svelte-1ob7tba"><div class="card-icon svelte-1ob7tba">🤝</div> <h3 class="svelte-1ob7tba">Tech Career Fair</h3> <p class="svelte-1ob7tba">Connect with local tech companies and discover career opportunities
					in Augusta's growing tech sector.</p> <button class="btn btn-secondary" disabled>Coming Soon</button></div> <div class="whats-next-card svelte-1ob7tba"><div class="card-icon svelte-1ob7tba">🎓</div> <h3 class="svelte-1ob7tba">Student Mentorship</h3> <p class="svelte-1ob7tba">Bridging the gap between education and industry through mentorship
					programs and workshops.</p> <button class="btn btn-secondary" disabled>Coming Soon</button></div></div></div></section>`;
}
export {
  _page as default
};
