import { h as head } from "../../../chunks/index2.js";
import { t as transparentLogo } from "../../../chunks/logo-transparent.js";
import { a as attr } from "../../../chunks/attributes.js";
function _page($$payload) {
  head($$payload, ($$payload2) => {
    $$payload2.title = `<title>Contact - Tech Talk Augusta</title>`;
    $$payload2.out += `<meta name="description" content="Get in touch with Tech Talk Augusta. We'd love to hear from you about events, partnerships, or any questions you may have."> <meta name="keywords" content="Contact Us, Tech Talk Augusta, Get in Touch, Augusta Tech Community"> <meta property="og:title" content="Contact - Tech Talk Augusta"> <meta property="og:description" content="Get in touch with Tech Talk Augusta. We'd love to hear from you about events, partnerships, or any questions you may have."> <meta property="og:image" content="https://techtalkaugusta.com/images/og-image.jpg"> <meta property="og:url" content="https://techtalkaugusta.com/contact">`;
  });
  $$payload.out += `<section class="hero svelte-ycyo5h"><div class="container"><div class="hero-content svelte-ycyo5h"><img${attr("src", transparentLogo)} alt="Tech Talk Augusta Logo" class="hero-logo svelte-ycyo5h"> <h1>Get in Touch</h1> <p class="lead svelte-ycyo5h">Have questions about our events, want to partner with us, or just want to say hello? We'd love to hear from you!</p></div></div></section> <section class="contact-section svelte-ycyo5h"><div class="container"><div class="contact-grid svelte-ycyo5h"><div class="contact-info svelte-ycyo5h"><h2>Other Ways to Connect</h2> <div class="contact-methods svelte-ycyo5h"><div class="contact-method svelte-ycyo5h"><h3 class="svelte-ycyo5h">Discord Community</h3> <p class="svelte-ycyo5h">Join our Discord server to connect with other members of the Augusta tech community.</p> <a href="https://discord.gg/techtalkaugusta" class="btn btn-primary" target="_blank" rel="noopener noreferrer">Join Discord</a></div> <div class="contact-method svelte-ycyo5h"><h3 class="svelte-ycyo5h">Social Media</h3> <p class="svelte-ycyo5h">Follow us on social media for updates and community highlights.</p> <div class="social-links svelte-ycyo5h"><a href="https://twitter.com/techtalkaugusta" target="_blank" rel="noopener noreferrer" class="svelte-ycyo5h">Twitter</a> <a href="https://linkedin.com/company/techtalkaugusta" target="_blank" rel="noopener noreferrer" class="svelte-ycyo5h">LinkedIn</a> <a href="https://github.com/techtalkaugusta" target="_blank" rel="noopener noreferrer" class="svelte-ycyo5h">GitHub</a></div></div> <div class="contact-method svelte-ycyo5h"><h3 class="svelte-ycyo5h">Email</h3> <p class="svelte-ycyo5h">For direct inquiries, you can reach us at:</p> <a href="mailto:hello@techtalkaugusta.com" class="email-link svelte-ycyo5h">hello@techtalkaugusta.com</a></div></div></div> <div class="contact-form svelte-ycyo5h"><h2 class="svelte-ycyo5h">Send Us a Message</h2> <p class="svelte-ycyo5h">Fill out the form below and we'll get back to you as soon as possible.</p> <div class="notion-form svelte-ycyo5h"><iframe src="https://wax-warbler-fff.notion.site/ebd/14ebc6eec56680febb3fcd6d10e1cd94" width="100%" height="600" frameborder="0" allowfullscreen title="Contact form"></iframe></div></div></div></div></section>`;
}
export {
  _page as default
};
