name: Deploy Discord Bot to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'discord/**'  # Only trigger on changes to discord directory
  workflow_dispatch:  # Allows manual trigger

env:
  NODE_VERSION: '18.x'
  AZURE_WEBAPP_NAME: tech-talk-augusta-bot
  AZURE_WEBAPP_PACKAGE_PATH: './discord'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      working-directory: ./discord
      run: |
        npm ci
        npm run build --if-present

    - name: Zip artifact for deployment
      working-directory: ./discord
      run: zip -r ../release.zip ./* 

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: release.zip
        
    - name: Azure logout
      run: |
        az logout 