name: tech-talk-augusta-bot
schedules:
  - cron: "0 */12 * * *"  # Run every 12 hours to stay within free tier limits
    displayName: Keep alive
    always: true

trigger:
  - main

variables:
  NODE_VERSION: '18.x'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NODE_VERSION)
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(AZURE_SUBSCRIPTION)'
    appName: '$(APP_NAME)'
    package: '.'
    startUpCommand: 'npm start' 